#!/usr/bin/env bash                                                                                                                                       
# fix nginx listening on port 80                                                                                                                          
# Go to sites-enabled folder for Nginx
# if cd command fails for any reason, script should exit                                                                                                                 
cd /etc/nginx/sites-enabled/ || exit;                                                                                                                             
# Delete the default file                                                                                                                               
rm default;                                                                                                                                               
# Create symbolic link to the deafult file in sites-available                                                                                             
ln -s /etc/nginx/sites-available/default default;                                                                                                         
# Restart Nginx                                                                                                                                           
sudo service nginx restart
