#!/usr/bin/env bash
# prints text infinitely

while true; do
    case "$RANDOM" in
        *)
            echo "To infinity and beyond"
            ;;
    esac

    case "$RANDOM" in
        *)
            trap 'echo "I am invincible!!!"' SIGTERM 
            ;;
    esac

    sleep 2
done
