#!/usr/bin/env bash

# For loop to iterate over numbers from 1 to 100
for ((i=1; i<=100; i++))
do
  # print (FizzBuzz) if the number is a multiple of both 3 and 5
  if (( i % 3 == 0 && i % 5 == 0 )); then
    echo "FizzBuzz"
  # print (Fizz) if the number is a multiple of 3
  elif (( i % 3 == 0 )); then
    echo "Fizz"
  # print (Buzz)if the number is a multiple of 5
  elif (( i % 5 == 0 )); then
    echo "Buzz"
  # else display
  else
    echo "$i"
  fi
done
