#!/usr/bin/env bash
# Initializing the loop iterator

i=1

# Loop to print numbers from 1 to 20
while [ $i -lt 21 ]
do
  case $i in
    4)
      echo "$i"
      echo "bad luck from China"
      ;;
    9)
      echo "$i"
      echo "bad luck from Japan"
      ;;
    17)
      echo "$i"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac

# increment
  i=$((i + 1))
done
