#!/usr/bin/env bash
# Initializing the loop iterator

i=0

# While loop to print numbers from 1 to 118
while [ $i -le 779 ]; do

  if [ $((i % 60)) -eq 0 ]; then
    echo "Hour: $((i / 60))"
  else
    echo "$((i % 60))"
  fi

  # Increment
  i=$((i + 1))
done
