#!/usr/bin/env bash
# Initializing the loop iterator

i=0

# While loop to print numbers from 1 to 118
while [ $i -le 119 ]
do
  if [ $i -eq 0 ]; then
    echo "Hour: 0"
  elif [ $i -le 59 ]; then
    echo "$i"
  elif [ $i -eq 60 ]; then
    echo "Hour: 1"
  else
    echo "$((i - 60))"
  fi

  # Increment
  i=$((i + 1))
done
