#!/usr/bin/env bash
# loop to iterate overdirectory

for file in *
do
  # Check if the file is not hidden
  if [[ $file != .* ]]; then
    # Get the part of the name after the first dash
    name=$(echo "$file" | cut -d '-' -f 2-)
    echo "$name"
  fi
done
