#!/usr/bin/env bash
# does file exist?

if [ -e "school" ]; then
    echo "school file exists"

    # is file empty
    if [ ! -s "school" ]; then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi

    # is it a regular file
    if [ -f "school" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
