#!/usr/bin/env bash

# Update package list and install UFW
sudo apt update
sudo apt install ufw -y

# Allow SSH (port 22)
sudo ufw allow 22/tcp

# Allow HTTPS (port 443)
sudo ufw allow 443/tcp

# Allow HTTP (port 80)
sudo ufw allow 80/tcp

# Set the default policy to deny incoming connections
sudo ufw default deny incoming

# Enable the UFW firewall
sudo ufw enable

# Display the UFW status to verify the rules
sudo ufw status
